# Abstract {-}

New teachers face numerous challenges during their transition from teacher preparation programs into professional employment contexts (i.e., their induction period), and they seek support from a variety of sources. Teacher induction research has reported a “two worlds pitfall” caused by conflicting messages about what and how to teach from the academic world of the preparation program and the practical world of the teaching classroom (Feiman-Nemser & Buchmann, 1985). Further complicating teacher induction is the new reality that new teachers are no longer seeking help with their profession from just two worlds, but a universe of many worlds accessible through social media, an *edu-verse*. From interviews with new teachers (*n* = 9), I describe what supports for professional learning they seek during induction and how they use social media with the intention of seeking these supports. The reported findings will benefit new teachers, teacher educators, and mentors.

**Research Questions**

- RQ1. What reasons, if any, do new teachers report for seeking induction supports, and what reasons do they give, if any, for not seeking induction supports?
- RQ2. What supports for professional learning, if any, are new teachers seeking during induction?
- RQ3. What interpersonal connections do new teachers make when seeking supports for professional learning during induction?
- RQ4. How, if at all, do new teachers use social media as a modality to access supports for professional learning during induction?

**Keywords**

new teachers, induction, self-directed learning, professional learning networks, social media
