# Reasons for Seeking Induction Supports

I considered Bandura’s (2001b) three interconnected determinants of social cognitive theory (SCT), environmental, personal, and behavioral factors, when answering the first research question, “What reasons, if any, do new teachers report for seeking induction supports, and what reasons do they give, if any, for not seeking induction supports?” In the following paragraphs, I describe the environmental, personal, and behavioral factors reported by interview participants in this study.

## Environmental Factors

The first set of Bandura’s (2001b) SCT determinants are environmental factors related to new teachers’ context. I identified three themes related to environmental factors: new teachers’ challenges related scarcity of resources, overabundance of resources, and change.

Scarcity of resources manifested in the absence of curriculum, missing classroom materials, poor physical conditions of school, or a new teachers’ limited budget. Anne spoke at length and in detail about her urban school’s challenging physical environment. Her classroom is in a modular trailer that has air conditioning but lacks insulation for cold Midwestern winters. During the day, she has to keep her personal belongings in sealable plastic bags so that she does not inadvertently take bugs home with her. Amelia, as an itinerant music teacher serving several schools in a suburban district, lacks a dedicated music classroom and can teach only with whatever supplies she can find herself and carry with her.

On the other end of the spectrum, some schools did provide resources (e.g., curriculum, classroom supplies, technology, funds for graduate school), but challenges sometimes arose from overabundance. An oversaturation of resources sometimes overwhelmed new teachers. For instance, Hallie described the process of sorting through materials left behind by her predecessor:

>I had a room chock full of like very old materials, like a bunch of garbage. There were some valuable things in there, but very few. So I had to spend multiple hours just cleaning junk out, things like an overhead projector things and other things that are just not helpful at all. But I found a couple like helpful resources for math and stuff.

For Julie, the overwhelming volume of resources was epitomized by one object in her classroom:

>There's a filing cabinet in my room that was in the corner; no one touched it. The teacher before the teacher I replaced had taught there for like 45 years. And that was his entire filing cabinet of work.

Julie took the time to look through the entire filing cabinet and was able to find a few useful resources. She moved the filing cabinet from the back corner of the classroom to beside her desk, and she began to mix in fresh assignments as well.

In addition to school-provided resources being overwhelming, new teachers also experienced them as constraining. For instance, Mike works in a wealthy suburban district and has been provided a detailed curriculum. However, Mike finds this environment to be stifling in its own way: 

>This is one of my biggest challenges. I feel very constrained. Especially in a high school math class, we have an insane amount of standards to cover. And standards are good, because you know, you should have certain goals to meet, and you should be able to say, "Today I did this objective," whatever you want to call it. But when you have the amount that you have as an educator, it takes any wiggle room out of the equation… That is my biggest concern for my teaching career: that I will get burnt out because all the fun stuff is stripped out. The kids don't actually want to learn it because of that, and it's not even useful for them for the most part.

Mike observed that environmental factors go beyond material needs to include systemic issues of what is expected of educators generally and new teachers specifically: “These problems are stemming from a system that is starting well before students come to me.” Mike suggested these systemic issues cannot be solved by more or better induction supports: “I have all of the best supports that you can ask for as an educator. And I still have these problems.”

A third area of environmental factors involved change, disruptions, and uncertainty experienced by new teachers. On one hand, change is inevitable when transitioning into a new career, as was the case of each of these new teachers. Simone expressed this sentiment well:

>I feel like I'm still a student, not just because I'm in graduate school. But education is always changing. There's always something new. We go to professional development of how we can teach English language learners and how we can deal with, with social and emotional issues and trauma in your class. So I just feel like I'm always learning.

However, new teachers also reported additional challenges related to change. The transition into teaching seemed especially challenging for Julie and Wallace, who started as new teachers mid-year. Amelia, as an itinerant music teacher, did not find out her final teaching assignments until October. Anne experienced a high degree of personnel turnover, including her principal and her grade level partner teacher. Anne and Simone both described being handed new curricula each year, and the process of adjusting to a new plan never seemed to stop. Simone was also asked to pilot new curricula:

>First year teaching, it was all new curriculum. And then, second year teaching, new science curriculum, rolling into the reading and writing curriculum, then I'm piloting a new math curriculum. So it's a lot, yeah, trying to adjust to that...

New teachers described numerous effects of so much change, including Wallace’s description of a physical manifestation of his stress: “I was clenching my teeth so hard that my mouth was getting sore from it, but it was just me trying to get through everything.”

## Personal Factors

The second set of Bandura’s (2001b) SCT determinants are personal factors specific to an individual new teacher. I identified two themes related to personal factors: teacher capital and teaching beliefs conflicting with those held by colleagues.

Teacher capital can be understood as resources priorly held by or inherent to a new teacher as they enter the teaching profession. These resources include *social capital* (i.e., resources related to interpersonal connections) and *cultural capital* (i.e., resources related to knowledge and skills). An example of social capital was Wallace’s ability to ask other teachers and staff for help during his first year, something he was more comfortable doing because he had worked on staff at the school prior to starting as a teacher. He also noted that being connected to colleagues on Facebook reinforced these in-school relationships by giving him additional understanding of his co-workers. 

Taylor and Blair demonstrated a lack of cultural capital. They both work as specialist teachers in wealthy private schools, albeit in different states, and they both reported having many material resources and supportive colleagues. However, because they did not study education as undergraduates, they felt like they were missing some foundational teaching skills. Taylor noted: “There's planning, there's preparation, but I think there's something completely different to understanding how to organize a class, how to organize a lesson, how to build that up throughout the entire year.” As a school educational technology specialist, Blair commented on lacking a teacher’s identity: 

>I didn't really view myself as an educator, but like, the second I walked into a school, I was Ms. Blair. And I'd never been called that in my life. And it's because kids don't care what my position is. The fact that I'm an adult in this building means I'm a teacher.

These teacher capital examples illustrate how new teachers sought induction supports because they knew who to ask, they felt like they were missing essential teaching skills, or because they were needing to step into a novel professional identity.

A second area of personal factors pertained to conflict, the tension between new teachers’ previously held beliefs about teaching and those encountered in their school of employment. This tension manifested in a variety of ways. For instance, Julie experienced dissonance with her school’s strict policy on classroom management and student discipline. She characterized school norms as “We run a tight ship,” with teachers expected to send students to a responsible thinking classroom (RTC) following any violation of classroom rules, even minor infractions. Julie disagreed with this policy and expressed her opinion to her principal: 

>I'm only going to do RTC when it gets to this point. I'm not going to do RTC every single day. That's just not something that I can justify. And for a lot of those kids, it doesn't work. I don't really see the success in it.

Hallie, as a first-year teacher, described dissonance with her more experienced colleagues around curricular issues: “I have one teacher who just wants to use curriculum from 30 years ago. And I'm just like, ‘I can't do it.’ There are just completely irrelevant things.” Hallie also advocated for the inclusion of more antiracism materials in the elementary school curriculum. When her colleagues complained about their students’ reactions to discussing racism during Black History Month, Hallie responded:

>Well, that's the problem. It's uncharted, and it's February. And now you're talking about Black people, because it's Black History Month, and you've never talked about race before. And you have one Black student in your class.

These examples illustrate how new teachers must choose the degree of conflict they are willing to have with colleagues around issues of student discipline or racism, among other important topics where educational thinking has changed in recent years.

## Behavioral Factors

The third set of Bandura’s (2001b) SCT determinants are behavioral factors related to new teachers’ activity patterns. I identified four themes related to behavioral factors: maintaining personal-professional boundaries, connecting socially, planning, and enacting practice.

New teachers’ desire to maintain boundaries between their personal and professional lives involved conscious choices to keep aspects of their personal and professional lives distinct. For instance, Simone talked about improving her time management as a new teacher:

>So at the beginning of the year, it was really rough for me. So when I first started teaching, I was doing plans week by week, I will plan my whole week out. And then this year, since I started the Master’s degree program, I didn't want to bring any work home, and I didn't want to stay late, and I'm not a early morning person. So then it was getting things done day by day.

In addition, because each of the new teachers I interviewed used social media in some capacity related to their teaching role, teachers’ personal and professional contexts could intersect, collide, and conflict in one digital space or app. New teachers consistently described how they worked to avoid this convergence effect of social media. Mike was one of the most regimented in his social media use and content consumption. He described:

>I just can't afford the time. I have to have time for my students, and I have to have time for myself. And if I don't have time for myself, then I'm doing them a disservice. I have to have that shut-off button.

Generally, new teachers reported using Facebook and Instagram to sustain personal relationships, but a few teachers reported using Facebook groups to access professional communities of teachers or Instagram to follow other teachers. Pinterest and TeachersPayTeachers, on the other hand, were viewed fully on the professional side. New teachers used these two platforms to find teaching resources when needed. Some teachers used Twitter for professional purposes only when required to for graduate school courses. Otherwise, Simone noted, “I use Twitter as my comedy,” and Taylor used Twitter to sustain a “decent following” of fans from her adjacent career as a professional athlete.

A consistent thread through new teachers’ discussions of social media was this desire to separate personal and professional. Julie succinctly summed up her approach: “I know what I'm getting myself into when I open each one of the apps.”

A second area of behavioral factors was connecting socially, activity that included both positive aspects of social glue and negative aspects of social comparison. New teachers reported positive social benefits of connecting with colleagues through professional learning communities (PLCs) in schools of teachers organized by grade level or subject. For instance, the physical education (PE) department in Taylor’s school shares an office, and PE teachers convene regularly throughout the day. The school policy is for departments to meet monthly, but other teachers joke that the PE department meets daily. Taylor described this PLC as a “tight-knit group” with a “group mentality” that functions not just as a source of teaching ideas, but a loyal in-group.

Mike described the importance of new teachers’ having social outlets for teaching-related frustrations:

>I vent for my mental health. I vent to other teachers and other people about this stuff. I would say, frequently, just to be honest. And that's scary to say, because I am at a premier school that has premier students, and it has great funding for electives and extracurriculars and resources and technology. Like, I couldn't be at a better school.

New teachers often described their social media use in connecting terms. For instance, Anne noted: “A lot of times, if I go to social media, it's for an outlet, for frustrations, and difficulties.” Simone talked about the benefit of getting perspective through connecting socially: “It's always nice to see what other teachers are dealing with in their district or their state. Like, ‘Are you experiencing these same things?’ It's nice to know that you're not the only one.”

However, new teachers also described how connecting socially can be detrimental. Anne, teaching under difficult circumstances with few resources and a challenging physical environment, noted the challenges of seeing teachers in other districts present pristine classrooms on social media:

>Back to the Instagram thing, I do follow some teacher accounts. Sometimes I feel like, it makes me feel like a crappy teacher, because I'm seeing them do all these things. And I'm like, “I'm tired right now. If I did all those things, I would either never sleep, or I would be just doing those things. I wouldn't be able to follow through with them and actually teach with those tools that they're spending hours making on the weekend.” And it just, it makes me feel like I should be doing more. But I already feel like I'm doing more than I can keep up with.

Julie perceived new teachers’ (and her own) social media use as primarily about sharing and finding resources. She expressed a desire for more genuine interaction and collaboration: “I wish there was more a way to use social media like, ‘Here's a problem I'm dealing with; can people help me with this problem?’”

A third area of behavioral factors was planning. All teachers prepare for teaching ahead of time, which includes generating ideas, creating curriculum, writing lesson plans, and finding appropriate resources. Taylor and Blair, without undergraduate teacher preparation, struggled with creating a semester-long teaching plan. However, they were not alone in this difficulty. Because her district did not assign a curriculum to follow, Hallie, who graduated from one of the top teacher preparation programs in the U.S., nevertheless described her internal process of deciding what to teach in her specific school: “What am I supposed to do? Like, what do you actually want me to do?” She also acknowledged the openness of her colleagues, but limitations remained: “There are teachers that are willing to help, but because my team doesn't do a lot of the actual same activity, it doesn't really help to share planning resources, always.” Julie was candid about this issue: “I feel like I filled a lot of gaps. If I couldn't find something, I'd go to social media to find it.”

Alongside challenges of unclear expectations and needing to fill gaps, an additional planning difficulty for new teachers is navigating the overwhelming number of possibilities of what and how to teach. New teachers’ efforts to seek induction supports from any sources possible, ranging from school colleagues to social media, sometimes result in too many ideas.

New teachers often turned to school colleagues for planning help, including team teachers, mentor teachers, and PLCs. However, Julie found the helpfulness of colleagues to be overwhelming at times: 

>I felt like a lot of teachers were saying, “Here, try this. Here, try this.” And I didn't really have the time to fully plan out units or plan out weeks at all. I just, there was no time for that. A lot of people were just trying to throw me ideas and there weren’t people I could really go to for ideas.

The unidirectional flow of ideas from colleagues to new teachers seemed to be part of the trouble for Julie. She said she would rather have people she could seek out when she was ready to work on planning and encountered a challenge.

In addition, new teachers often reported turning to social media to find teaching resources while they were planning. Pinterest and TeachersPayTeachers seemed to be the most popular platforms for this. New teachers described both browsing through potential resources as well as searching with a specific need in mind. Amelia found TeachersPayTeachers to be a good source for plans to leave for substitute teachers and a district Facebook group to be a good place to ask for curriculum and materials.

A fourth area of behavioral factors was enacting practice, where new teachers seek to improve their instruction and interactions with students in the classroom. New teachers’ exhibited this theme when they described issues like classroom management, student engagement, and helping students. For instance, Amelia, Anne, and Julie each talked extensively about difficult classroom management situations they had encountered, and how they worked through these in conversation with colleagues, mentor teachers, and principals. For instance, Hallie talked with her PLC about “embedding real learning ideas” in discussions of current events like voting instead of “reading a story and making it work with a standard.” She went on to say how figuring out her teaching practice in this way helps her as well as her students: “I enjoy my job a lot more teaching real things, and I think students come away with it more than just memorizing, and being able to do a standard on a standardized test.”

New teachers noted that social media help enact practice too. Taylor found that YouTube videos are especially use to demonstrate activities for her PE classes. Julie noted she did not always turn to social media to figure out what to teach, but sometimes to refine an existing plan: “I still do a lot of that stuff, just somewhat in the same ways and somewhat with some extra TeachersPayTeachers flair.”
