# Types of Induction Supports for Professional Learning

I approached the second research question, “What supports for professional learning, if any, are new teachers seeking during induction?,” by drawing from Bandura’s (2001a) agentic perspective on SCT to distinguish between required and voluntary supports. In the following paragraphs, I report how new teachers described their assigned, latent, and self-directed supports. 

## Assigned Supports

Of the numerous induction supports described by new teachers, many were assigned to them. In many cases, new teachers appreciated assigned supports such as mentor teachers, PLCs, new teacher cohorts, and curricula. For instance, Julie, as an 8th-grade English Language Arts teacher, reflected on how she was supported in different ways by three different mentor teachers during her first three years of teaching:

>I had our eighth grade science teacher for part of my mentorship too, which was nice because she was teaching the same kids that I was. So it was more like we communicated about students there. And seventh grade English, I communicate more about English stuff there. And then with the sixth grade history teacher, we don't really have much in common, but it was nice to just see a completely different successful way of teaching… I like having all those different mentors.

However, there were also supports assigned to new teachers that they found to be unhelpful or unnecessary. Anne’s school assigned curricula for different subjects, but continuously introducing new curricula was unhelpful:

>It seems like every year we get some kind of new curriculum. I know my first year we switched to all new reading and writing, well it was reading, writing, and word study. Then the next year, it wasn't completely new, but they revamped our math. This year, they dumped our science program, got a new science program. And it sounds like social studies is in the works for next year.

In addition, paraeducators assigned to support new teachers were not always helpful. Simone, a 1st Grade teacher, recounted a support meeting with a social worker, a literacy coach, and a several special education teachers. She was telling them about her unsuccessful attempts to engage one of her students, and this is how she recounted the meeting:

>The one doing most of the talking just like, “With this kid, I don't have a lot to say.” And I just felt like... [audibly sighs]. Yeah, so basically she said, for him, I have to turn everything into a game. He loves to play. So basically like being in a preschool. So while the other kids are sitting at their desk, writing on their papers, I have to turn this into a interactive thing for this child, which is a lot of work to do for one child. I was keeping lots of data on this student, where I could tally three behaviors to focus on, tally how often he shows these behaviors. And then l asked myself, “What am I doing this for?” I've talked to the parents, I've told them… So I would just say I'm doing this for no reason.

Simone found her interactions with paraeducators to be patronizing and unhelpful, creating busywork for her that she did not believe would benefit her students.

## Latent Supports

New Teachers identified many additional potential supports besides those that had been formally assigned to them. In some cases, they recognized a support’s potential helpfulness but chose not to use it. New teachers chose not to pursue these latent supports for a variety of reasons. For instance, Amelia voiced how helpful it would be to have a district-wide gathering of music teachers, but it may not have occurred to her that she could have helped to organize this group. Mike recognized that social media like Twitter represented opportunities for support for new teachers, but he chose not to use Twitter because his primary concern was managing his time. Similarly, Hallie and Simone were more compelled by personal-professional boundaries than social media benefits. Like Mike, Taylor saw Twitter’s potential for interactions amongst new teachers but chose not to pursue these because she perceived Twitter discourse as being constrained by the platform’s limits on message length.

Because these latent supports were not assigned as part of the new teachers’ job requirements, they represented opportunities for self-directed learning that could be on-demand, just-in-time, and as-needed. However, this could alternatively be viewed as volunteering personal time to work. Blair was blunt about this:

>There were times when different teachers, like that one teacher I really liked working with, would say, “Oh, if you ever have downtime, you can just come to my classroom and observe or help out so you get more experience.” And, and in the moment I was like, “Yeah, that's a great idea!” But then like, when the time actually came, I was like, “No, I don't want to go work when I'm not working.”

In this case, Blair admired the teacher making this invitation. Her reticence to pursue these supports was linked more to her limited capacity as a new teacher: “I feel like there are more things like that, when there is an opportunity to learn more, that I don't take because I don't feel like it, because I would rather do nothing.”

## Self-directed Supports

Still, despite the demands of transitioning into a new job, new teachers reported many examples of how they pursued voluntary, self-directed professional learning. They pursued informal avenues within the school building when they sought out colleagues during planning periods or in the teachers’ lounge. They intentionally chose to follow and connect with other teachers through social media. They enrolled in graduate programs of education and participated in regional and national organizations that supported their teaching. One of my final questions in each interview was whether there were any additional supports the new teacher could think of but did not pursue. Wallace captured the sentiment of self-directed learning:

>No, I pretty much always was reaching out to whoever would help me. I kind of knew, like you said, the challenges were there and I was looking out for help, any way I could get it at that time… I feel like it's a cheap answer, but I just can't think of a time that I didn't ask someone for help. Even if it was my wife, or I don't know... I can't think of any time that I would just fail and just accept it and not reach out.

Wallace’s reflections exemplify the drive exhibited by the new teachers I interviewed. Although some teachers did not pursue every voluntary opportunity for induction support available to them, each of these teachers did take on more than was required in their job description.

In sum, the types of induction supports sought by new teachers can be understood as either required or voluntary. New teachers seemed to benefit less from required supports that they did not perceive as useful (e.g., staff meetings or professional development covering topics irrelevant to them). New teachers also chose to pursue many voluntary, self-directed avenues of support as well, including many through social media. But when they perceived the challenges (e.g., time, energy, money) to outweigh the benefits, new teachers did not pursue those supports.
