# Interpersonal Connections for Induction Supports

I approached the third research question, “What interpersonal connections do new teachers make when seeking supports for professional learning during induction?,” by considering *interpersonal connections for induction support* in light of previous work on teacher networks (e.g., Bartell et al., 2019; März & Kelchtermans, 2020), noting the location of connections as occurring within a new teacher’s school or outside.

## In-school Connections

In many cases, new teachers sought induction supports through relationships inside their school building. These included both formally required supports such as mentor teachers and PLCs (whether organized by grade level or subject) as well as informal supports initiated by the new teacher, such as talking to colleagues in the teachers’ lounge.

These in-school connections were also reinforced through social media modalities. Wallace worked at his school for several years as a staff member prior to being hired to teach midyear. He was connected to many school colleagues on Facebook, and believed that having this additional source of personal connection (e.g., seeing photos of coworkers’ children) improved the ways he was supported during his transition into teaching. As another example, Wallace described how fellow 10th-grade English teachers in his school used a Google Classroom shell to share teaching ideas and resources with each other.

## Out-of-school Connections

New teachers sought induction supports beyond their school buildings as well, whether local or more far-reaching. At the local district level, there were some formally required supports for new teachers, such as district-wide professional development gatherings. Amelia described several informal initiatives in her district. She participated in a Facebook Group composed of music teachers in the district, where colleagues could post questions and requests for the sharing of musical instruments. Amelia’s PLC included teachers from 10 schools and, at the time of our interview, had just begun using Microsoft Teams as “a way for us to meet and actually talk about stuff… a way for us to communicate in the interim between our two-week meetings.”

New teachers described turning to friends and family members for encouragement and even ideas when those connections were themselves experienced educators. New teachers also joined groups organized to support teachers. For example, during her undergraduate years, Simone joined a sorority for African American women, and after graduation, she continued to attend local gatherings of sorority sisters in her city. Many members are teachers, and Simone found them to be an important emotional and professional support as she started teaching. Mike attended a local group for new teachers that was organized as an informal partnership between his school district and the teacher preparation program at the nearby research university. Mike was also a member of a prestigious, national organization whose mission is to provide high quality professional development in problem-based learning to a select group of math teachers. These supports are different types of distributed networks, which expand beyond teachers’ school building but still rely on face-to-face meetups.

Finally, new teachers also sought induction supports through networks hosted online. They looked to social media for opportunities to vent their frustrations, seek solidarity, exchange ideas, and find resources. For instance, Taylor subscribed to another PE teacher’s YouTube channel to get inspiration for her classes as well as visual instructions for how to teach various activities:

>He does these amazing YouTube videos that break down by stages and how to run different drills and games for PE, and I think that's probably the most helpful thing that I've seen online.

Simone participated in Facebook group teachers from all over the U.S.:

>It’s always nice to see what other teachers are dealing with in their district or their state like, “Are you, are you experiencing these same things?” And they are, and it's nice to know that you're not the only one.

Simone appreciated not just the ideas and resources from this group, but also the perspective they were able to offer her. She was reminded that she was not alone feeling the way she did, and that there were other ways to teach besides what she had experienced in her own school and district. These perspectives seemed especially important to Simone as a Black teacher whose preparation program was overwhelmingly white, and whose school of employment was diverse but under-resourced.
