# References {-}

Bandura, A. (2001a). Social cognitive theory: An agentic perspective. *Annual Review of Psychology, 52*(1), 1-26. https://doi.org/10.1146/annurev.psych.52.1.1

Bandura, A. (2001b). Social cognitive theory of mass communication. *Media Psychology, 3*(3), 265-299. https://doi.org/10.1207/S1532785XMEP0303_03

Bartell, T., Cho, C., Drake, C., Petchauer, E., & Richmond, G. (2019). Teacher agency and resilience in the age of neoliberalism. *Journal of Teacher Education, 70*(4), 302-305. https://doi.org/10.1177/0022487119865216

Feiman-Nemser, S., & Buchmann, M. (1985). Pitfalls of experience in teacher preparation. *Teachers College Record, 87*, 53–65.

März, V., &, Kelchtermans, G. (2020). The networking teacher in action: A qualitative analysis of early career teachers' induction process. *Teaching and Teacher Education, 87*, 1-14. https://doi.org/10.1016/j.tate.2019.102933

Prestridge, S. (2019). Categorising teachers’ use of social media for their professional learning: A self-generating professional learning paradigm. *Computers & Education, 129*, 143-158. https://doi.org/10.1016/j.compedu.2018.11.003
